repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--max-args=7", # Allow up to 10 arguments
            "--max-locals=16", # Allow up to 16 local variables
            "--ignore=tests", # Ignore the tests directory
          ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest
        types: [python]
        args: ["-v"]