site_name: Dataset Translation for PT-BR using Open Source Models
theme:
  name: material
  palette:
    primary: red
  language: pt

repo_name: "H-IAAC/translate-dataset/"
repo_url: "https://github.com/H-IAAC/translate-dataset"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
